# -*- coding: utf-8 -*-
"""automate_Daniel Bayu Wicaksono

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15h-1u00zJe0fmq5FbJf6i883C3G8oLNF
"""

import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import StandardScaler, LabelEncoder

def load_dataset(path):
    return pd.read_csv(path)

def drop_id_columns(df):
    return df.drop(
        columns=[
            'TransactionID',
            'AccountID',
            'DeviceID',
            'MerchantID',
            'IP Address'
        ],
        errors='ignore'
    )

def handle_missing_and_duplicates(df):
    df = df.dropna()
    df = df.drop_duplicates()
    return df

def scale_numeric_features(df):
    numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
    scaler = StandardScaler()
    df[numeric_cols] = scaler.fit_transform(df[numeric_cols])
    return df

def encode_categorical_features(df):
    categorical_cols = df.select_dtypes(include=['object']).columns
    encoders = {}

    for col in categorical_cols:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])
        encoders[col] = le

    return df, encoders

def handle_outliers_iqr(df):
    Q1 = df.quantile(0.25)
    Q3 = df.quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df = df[~((df < lower) | (df > upper)).any(axis=1)]
    return df

def binning_features(df):
    # Binning usia
    bins_age = [0, 25, 45, 100]
    labels_age = ['Muda', 'Dewasa', 'Senior']
    df['CustomerAge_binned'] = pd.cut(
        df['CustomerAge'], bins=bins_age, labels=labels_age
    )

    # Binning jumlah transaksi
    bins_amount = [-np.inf, 100, 1000, np.inf]
    labels_amount = ['Kecil', 'Sedang', 'Besar']
    df['TransactionAmount_binned'] = pd.cut(
        df['TransactionAmount'], bins=bins_amount, labels=labels_amount
    )

    le = LabelEncoder()
    df['CustomerAge_binned'] = le.fit_transform(df['CustomerAge_binned'])
    df['TransactionAmount_binned'] = le.fit_transform(df['TransactionAmount_binned'])

    return df

def preprocessing_pipeline(input_path, output_path):
    output_dir = os.path.dirname(output_path)
    if output_dir != "":
        os.makedirs(output_dir, exist_ok=True)

    df = load_dataset(input_path)
    df = drop_id_columns(df)
    df = handle_missing_and_duplicates(df)
    df = scale_numeric_features(df)
    df, _ = encode_categorical_features(df)
    df = handle_outliers_iqr(df)
    df = binning_features(df)

    df.to_csv(output_path, index=False)
    return df

if __name__ == "__main__":
    input_path = "https://drive.google.com/uc?id=1gnLO9qvEPqv1uBt1928AcsCmdvzqjC5m"
    output_path = "bank_transactions_preprocessing.csv"

    df_ready = preprocessing_pipeline(input_path, output_path)

    print("Preprocessing otomatis selesai")
    print("Dataset siap dilatih")
    print("Jumlah data akhir:", df_ready.shape)