# -*- coding: utf-8 -*-
"""modelling_tuning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DBSeUy4BWA7t5VaOcPt0js6Qs6Xdbqny
"""

import os
import json
import pandas as pd
import mlflow
import mlflow.sklearn

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

data_path = "bank_transactions_preprocessing.csv"
df = pd.read_csv(data_path)

X = df.select_dtypes(include=["int64", "float64"])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

mlflow.set_experiment("KMeans_Tuning_Experiment")

best_score = -1
best_k = None

# Hyperparameter tuning
for k in [2, 3, 4, 5, 6]:
    with mlflow.start_run(run_name=f"KMeans_k_{k}"):

        model = KMeans(
            n_clusters=k,
            random_state=42
        )
        model.fit(X_scaled)

        labels = model.labels_
        score = silhouette_score(X_scaled, labels)

        # Log parameter & metric
        mlflow.log_param("n_clusters", k)
        mlflow.log_metric("silhouette_score", score)

        # Log model
        mlflow.sklearn.log_model(
            sk_model=model,
            artifact_path="model"
        )

        # Create metric_info.json
        metric_info = {
            "metric_name": "silhouette_score",
            "value": score,
            "n_clusters": k,
            "description": "Silhouette Score for KMeans clustering"
        }

        os.makedirs("artifacts", exist_ok=True)
        metric_path = "artifacts/metric_info.json"
        with open(metric_path, "w") as f:
            json.dump(metric_info, f, indent=4)

        mlflow.log_artifact(metric_path)

        # Create estimator.html
        estimator_html = f"""
        <html>
        <head><title>KMeans Estimator</title></head>
        <body>
            <h1>KMeans Model Summary</h1>
            <ul>
                <li>Number of clusters: {k}</li>
                <li>Random state: 42</li>
                <li>Silhouette Score: {score:.4f}</li>
            </ul>
        </body>
        </html>
        """

        estimator_path = "artifacts/estimator.html"
        with open(estimator_path, "w") as f:
            f.write(estimator_html)

        mlflow.log_artifact(estimator_path)

        # Track best model
        if score > best_score:
            best_score = score
            best_k = k

print("Best k:", best_k)
print("Best Silhouette Score:", best_score)