# -*- coding: utf-8 -*-
"""modelling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-R2z9nZTMq-7K3wng7zlTE4HQGHssGu3
"""

import pandas as pd
import mlflow
import mlflow.sklearn

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

# Load dataset hasil preprocessing
data_path = "bank_transactions_preprocessing.csv"
df = pd.read_csv(data_path)

# Pisahkan fitur
X = df.select_dtypes(include=["int64", "float64"])

# Scaling ulang (aman untuk modelling)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

mlflow.set_experiment("KMeans_Base_Model")
mlflow.sklearn.autolog()

with mlflow.start_run(run_name="KMeans_Base"):

    model = KMeans(
        n_clusters=3,
        random_state=42
    )
    model.fit(X_scaled)

    labels = model.labels_
    score = silhouette_score(X_scaled, labels)

    # Tetap log manual silhouette score
    mlflow.log_metric("silhouette_score", score)

print("Silhouette Score:", score)